const pom = (2)=>{
const pom = (2)=>{

const pom = (2)=>{console.log(2);
const pom = (2)=>{console.log(2);return a;}
const myError = Error("This is My Error");
throw my Error;
try{
throw myError;
}catch(e){
console.log(e);
}finally{
console.log('後処理');
}